export default async function Home() {
  return (
    <div className="mb-12 flex flex-col items-center px-4 pt-6">
      <h1 className="mb-2 text-center">Wrapup</h1>
      {/* QUICK STATS */}
      <table>
        <thead>
          <tr>
            <th></th>
            <th>in-person</th>
            <th>remote-box</th>
            <th>remote</th>
            <th>total</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>teams</th>
            <td>40</td>
            <td>49</td>
            <td>271</td>
            <td>360</td>
          </tr>
          <tr>
            <th>finishers</th>
            <td>12</td>
            <td>27</td>
            <td>47</td>
            <td>86</td>
          </tr>
          <tr>
            <th>action meta solves</th>
            <td>29</td>
            <td>38</td>
            <td>139</td>
            <td>206</td>
          </tr>
          <tr>
            <th>participants</th>
            <td>247</td>
            <td>129</td>
            <td>487</td>
            <td>863</td>
          </tr>
          <tr>
            <th>hints asked</th>
            <td>163</td>
            <td>205</td>
            <td>908</td>
            <td>1276</td>
          </tr>
          <tr>
            <th>guesses</th>
            <td>3751</td>
            <td>8172</td>
            <td>23521</td>
            <td>35444</td>
          </tr>
          <tr>
            <th>solves</th>
            <td>1118</td>
            <td>1936</td>
            <td>5343</td>
            <td>8397</td>
          </tr>
        </tbody>
      </table>
      {/* TEAM STATS */}
      {/* fewest guesses */}
      <table>
        <thead>
          <tr>
            <th>display_name</th>
            <th>guess_count</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Casabllama</td>
            <td>59</td>
          </tr>
          <tr>
            <td>The Wob Blizzards</td>
            <td>105</td>
          </tr>
          <tr>
            <td>The Greater Embarrassment Community Theater</td>
            <td>105</td>
          </tr>
          <tr>
            <td>Living Off Hope</td>
            <td>115</td>
          </tr>
          <tr>
            <td>Husky Hunters</td>
            <td>124</td>
          </tr>
          <tr>
            <td>Cardinality</td>
            <td>129</td>
          </tr>
          <tr>
            <td>plugh</td>
            <td>139</td>
          </tr>
          <tr>
            <td>Theatre Screen's Bright Illumination</td>
            <td>143</td>
          </tr>
          <tr>
            <td>Lefty</td>
            <td>146</td>
          </tr>
          <tr>
            <td>come back to us later</td>
            <td>146</td>
          </tr>
        </tbody>
      </table>
      {/* most guesses */}
      <table>
        <thead>
          <tr>
            <th>display_name</th>
            <th>guess_count</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>🍓➡️🐢</td>
            <td>689</td>
          </tr>
          <tr>
            <td>Hunters Around The World</td>
            <td>684</td>
          </tr>
          <tr>
            <td>Cacheiras</td>
            <td>591</td>
          </tr>
          <tr>
            <td>希望404</td>
            <td>469</td>
          </tr>
          <tr>
            <td>Les Gaulois</td>
            <td>460</td>
          </tr>
          <tr>
            <td>AHAMILTON RB.GY/TC4L8X CCAPAC APU #1 FAN + friends</td>
            <td>420</td>
          </tr>
          <tr>
            <td>the riddlers</td>
            <td>419</td>
          </tr>
          <tr>
            <td>Puzzle Solution Doxxers</td>
            <td>414</td>
          </tr>
          <tr>
            <td>Amateur Hour</td>
            <td>399</td>
          </tr>
          <tr>
            <td>何以为我</td>
            <td>393</td>
          </tr>
        </tbody>
      </table>
      {/* fewest hints */}
      <table>
        <thead>
          <tr>
            <th>display_name</th>
            <th>hint_count</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>chat</td>
            <td>0</td>
          </tr>
          <tr>
            <td>C-t Fillers</td>
            <td>0</td>
          </tr>
          <tr>
            <td>Casabllama</td>
            <td>0</td>
          </tr>
          <tr>
            <td>Please Clap</td>
            <td>0</td>
          </tr>
          <tr>
            <td>Double Award Nominee</td>
            <td>0</td>
          </tr>
          <tr>
            <td>Living Off Hope</td>
            <td>0</td>
          </tr>
          <tr>
            <td>Cardinality</td>
            <td>0</td>
          </tr>
          <tr>
            <td>Ultimate Brownies</td>
            <td>0</td>
          </tr>
          <tr>
            <td>Red Carpet Herrings 🎏</td>
            <td>0</td>
          </tr>
          <tr>
            <td>Dreamer Spinning Suspended Disbelief</td>
            <td>0</td>
          </tr>
          <tr>
            <td>⡫ I GUESS WE CAN'T ALL SIT NEXT TO EACH OTHER</td>
            <td>0</td>
          </tr>
          <tr>
            <td>SeptaCube</td>
            <td>0</td>
          </tr>
          <tr>
            <td>simplicissimus</td>
            <td>1</td>
          </tr>
          <tr>
            <td>Tricksters</td>
            <td>1</td>
          </tr>
          <tr>
            <td>Mobius Strippers</td>
            <td>1</td>
          </tr>
        </tbody>
      </table>
      {/* most hints */}
      <table>
        <thead>
          <tr>
            <th>display_name</th>
            <th>hint_count</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Alteleid</td>
            <td>24</td>
          </tr>
          <tr>
            <td>何以为我</td>
            <td>21</td>
          </tr>
          <tr>
            <td>More About Vikings</td>
            <td>21</td>
          </tr>
          <tr>
            <td>Turtle Power</td>
            <td>20</td>
          </tr>
          <tr>
            <td>Hunters Around The World</td>
            <td>20</td>
          </tr>
          <tr>
            <td>Livin’ Covida Loca</td>
            <td>19</td>
          </tr>
          <tr>
            <td>Hong Kong Guy My</td>
            <td>19</td>
          </tr>
          <tr>
            <td>Intervarsi-Teammate: Slowdown Showtime!</td>
            <td>18</td>
          </tr>
          <tr>
            <td>Team Conundrum</td>
            <td>18</td>
          </tr>
          <tr>
            <td>Team Peggle</td>
            <td>18</td>
          </tr>
        </tbody>
      </table>
      {/* most hints + follow-ups */}
      <table>
        <thead>
          <tr>
            <th>display_name</th>
            <th>total_hint_count</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Hunters Around The World</td>
            <td>58</td>
          </tr>
          <tr>
            <td>Alteleid</td>
            <td>53</td>
          </tr>
          <tr>
            <td>Livin’ Covida Loca</td>
            <td>43</td>
          </tr>
          <tr>
            <td>the riddlers</td>
            <td>42</td>
          </tr>
          <tr>
            <td>Puzzle Solution Doxxers</td>
            <td>36</td>
          </tr>
          <tr>
            <td>helppuzzles</td>
            <td>35</td>
          </tr>
          <tr>
            <td>何以为我</td>
            <td>34</td>
          </tr>
          <tr>
            <td>Hong Kong Guy My</td>
            <td>32</td>
          </tr>
          <tr>
            <td>Maxwell Rose</td>
            <td>32</td>
          </tr>
          <tr>
            <td>stɹeɪjə maɪt</td>
            <td>30</td>
          </tr>
        </tbody>
      </table>
      {/* PUZZLE STATS */}
      {/* primary stats */}
      <table>
        <thead>
          <tr>
            <th>id</th>
            <th>guesses</th>
            <th>solves</th>
            <th>backsolves</th>
            <th>hints</th>
            <th>hints + follow-ups</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>a-fistful-of-cards</td>
            <td>350</td>
            <td>212</td>
            <td>85</td>
            <td>5</td>
            <td>5</td>
          </tr>
          <tr>
            <td>a-fistful-of-cards-ii</td>
            <td>190</td>
            <td>158</td>
            <td>17</td>
            <td>2</td>
            <td>2</td>
          </tr>
          <tr>
            <td>a-fistful-of-cards-iii</td>
            <td>184</td>
            <td>131</td>
            <td>15</td>
            <td>2</td>
            <td>2</td>
          </tr>
          <tr>
            <td>a-fistful-of-cards-iv</td>
            <td>420</td>
            <td>95</td>
            <td>12</td>
            <td>23</td>
            <td>33</td>
          </tr>
          <tr>
            <td>aha-erlebnis</td>
            <td>637</td>
            <td>138</td>
            <td>0</td>
            <td>35</td>
            <td>54</td>
          </tr>
          <tr>
            <td>are-you-sure</td>
            <td>229</td>
            <td>145</td>
            <td>4</td>
            <td>1</td>
            <td>1</td>
          </tr>
          <tr>
            <td>balloon-animals</td>
            <td>412</td>
            <td>179</td>
            <td>0</td>
            <td>10</td>
            <td>15</td>
          </tr>
          <tr>
            <td>barbie</td>
            <td>230</td>
            <td>118</td>
            <td>19</td>
            <td>38</td>
            <td>58</td>
          </tr>
          <tr>
            <td>beads</td>
            <td>579</td>
            <td>151</td>
            <td>27</td>
            <td>72</td>
            <td>112</td>
          </tr>
          <tr>
            <td>bluenos-puzzle-box</td>
            <td>321</td>
            <td>124</td>
            <td>8</td>
            <td>14</td>
            <td>23</td>
          </tr>
          <tr>
            <td>boring-plot</td>
            <td>191</td>
            <td>94</td>
            <td>0</td>
            <td>45</td>
            <td>72</td>
          </tr>
          <tr>
            <td>chain-letters</td>
            <td>216</td>
            <td>136</td>
            <td>15</td>
            <td>23</td>
            <td>37</td>
          </tr>
          <tr>
            <td>color-wheel</td>
            <td>338</td>
            <td>83</td>
            <td>11</td>
            <td>37</td>
            <td>56</td>
          </tr>
          <tr>
            <td>connect-the-dots</td>
            <td>788</td>
            <td>194</td>
            <td>15</td>
            <td>37</td>
            <td>51</td>
          </tr>
          <tr>
            <td>constellation</td>
            <td>472</td>
            <td>93</td>
            <td>3</td>
            <td>29</td>
            <td>39</td>
          </tr>
          <tr>
            <td>cutting-room-floor</td>
            <td>400</td>
            <td>86</td>
            <td>0</td>
            <td>43</td>
            <td>62</td>
          </tr>
          <tr>
            <td>drop-the</td>
            <td>297</td>
            <td>206</td>
            <td>0</td>
            <td>5</td>
            <td>8</td>
          </tr>
          <tr>
            <td>eye-of-the-storm</td>
            <td>184</td>
            <td>127</td>
            <td>1</td>
            <td>30</td>
            <td>49</td>
          </tr>
          <tr>
            <td>eye-spy</td>
            <td>4431</td>
            <td>108</td>
            <td>15</td>
            <td>16</td>
            <td>21</td>
          </tr>
          <tr>
            <td>eye-to-eye</td>
            <td>124</td>
            <td>97</td>
            <td>0</td>
            <td>3</td>
            <td>6</td>
          </tr>
          <tr>
            <td>filming-schedule</td>
            <td>337</td>
            <td>241</td>
            <td>7</td>
            <td>5</td>
            <td>5</td>
          </tr>
          <tr>
            <td>financial-crimes-3</td>
            <td>272</td>
            <td>112</td>
            <td>13</td>
            <td>12</td>
            <td>17</td>
          </tr>
          <tr>
            <td>find-ben</td>
            <td>603</td>
            <td>232</td>
            <td>22</td>
            <td>7</td>
            <td>8</td>
          </tr>
          <tr>
            <td>fractal-shanty</td>
            <td>396</td>
            <td>163</td>
            <td>70</td>
            <td>31</td>
            <td>53</td>
          </tr>
          <tr>
            <td>fridge-magnets</td>
            <td>207</td>
            <td>93</td>
            <td>1</td>
            <td>3</td>
            <td>4</td>
          </tr>
          <tr>
            <td>genetic-counseling</td>
            <td>193</td>
            <td>111</td>
            <td>15</td>
            <td>2</td>
            <td>3</td>
          </tr>
          <tr>
            <td>hand-letters</td>
            <td>167</td>
            <td>143</td>
            <td>1</td>
            <td>4</td>
            <td>6</td>
          </tr>
          <tr>
            <td>heist</td>
            <td>405</td>
            <td>235</td>
            <td>60</td>
            <td>14</td>
            <td>16</td>
          </tr>
          <tr>
            <td>heist-ii</td>
            <td>184</td>
            <td>164</td>
            <td>6</td>
            <td>4</td>
            <td>5</td>
          </tr>
          <tr>
            <td>heist-iii</td>
            <td>186</td>
            <td>143</td>
            <td>10</td>
            <td>5</td>
            <td>8</td>
          </tr>
          <tr>
            <td>identify-the-piece</td>
            <td>4249</td>
            <td>131</td>
            <td>6</td>
            <td>30</td>
            <td>51</td>
          </tr>
          <tr>
            <td>imagine</td>
            <td>332</td>
            <td>108</td>
            <td>12</td>
            <td>34</td>
            <td>45</td>
          </tr>
          <tr>
            <td>international-neighbours</td>
            <td>769</td>
            <td>117</td>
            <td>61</td>
            <td>64</td>
            <td>104</td>
          </tr>
          <tr>
            <td>like-clockwork</td>
            <td>495</td>
            <td>93</td>
            <td>3</td>
            <td>53</td>
            <td>71</td>
          </tr>
          <tr>
            <td>lost-lyric</td>
            <td>355</td>
            <td>157</td>
            <td>28</td>
            <td>39</td>
            <td>49</td>
          </tr>
          <tr>
            <td>m-guards-n-doors-and-k-choices</td>
            <td>707</td>
            <td>156</td>
            <td>0</td>
            <td>9</td>
            <td>13</td>
          </tr>
          <tr>
            <td>narcissism</td>
            <td>360</td>
            <td>147</td>
            <td>0</td>
            <td>1</td>
            <td>1</td>
          </tr>
          <tr>
            <td>one-guard-screen</td>
            <td>540</td>
            <td>177</td>
            <td>4</td>
            <td>126</td>
            <td>159</td>
          </tr>
          <tr>
            <td>opening-sequences</td>
            <td>700</td>
            <td>143</td>
            <td>11</td>
            <td>15</td>
            <td>24</td>
          </tr>
          <tr>
            <td>peanuts</td>
            <td>302</td>
            <td>224</td>
            <td>5</td>
            <td>5</td>
            <td>7</td>
          </tr>
          <tr>
            <td>piecemeal</td>
            <td>274</td>
            <td>149</td>
            <td>2</td>
            <td>28</td>
            <td>36</td>
          </tr>
          <tr>
            <td>plagiarism</td>
            <td>726</td>
            <td>221</td>
            <td>1</td>
            <td>14</td>
            <td>15</td>
          </tr>
          <tr>
            <td>red-blue</td>
            <td>382</td>
            <td>88</td>
            <td>9</td>
            <td>33</td>
            <td>55</td>
          </tr>
          <tr>
            <td>secret-ingredient</td>
            <td>190</td>
            <td>121</td>
            <td>0</td>
            <td>2</td>
            <td>3</td>
          </tr>
          <tr>
            <td>six-degrees</td>
            <td>5307</td>
            <td>128</td>
            <td>0</td>
            <td>26</td>
            <td>32</td>
          </tr>
          <tr>
            <td>sound-of-music</td>
            <td>152</td>
            <td>98</td>
            <td>1</td>
            <td>4</td>
            <td>5</td>
          </tr>
          <tr>
            <td>ten-guards-ten-doors</td>
            <td>953</td>
            <td>208</td>
            <td>0</td>
            <td>37</td>
            <td>52</td>
          </tr>
          <tr>
            <td>the-compact-disc</td>
            <td>534</td>
            <td>87</td>
            <td>24</td>
            <td>40</td>
            <td>66</td>
          </tr>
          <tr>
            <td>the-final-heist</td>
            <td>214</td>
            <td>93</td>
            <td>6</td>
            <td>7</td>
            <td>7</td>
          </tr>
          <tr>
            <td>the-guard-and-the-door</td>
            <td>778</td>
            <td>138</td>
            <td>0</td>
            <td>51</td>
            <td>79</td>
          </tr>
          <tr>
            <td>the-snack-zone</td>
            <td>156</td>
            <td>136</td>
            <td>0</td>
            <td>2</td>
            <td>2</td>
          </tr>
          <tr>
            <td>two-guards-river</td>
            <td>246</td>
            <td>246</td>
            <td>0</td>
            <td>1</td>
            <td>3</td>
          </tr>
          <tr>
            <td>two-guards-two-doors</td>
            <td>782</td>
            <td>286</td>
            <td>5</td>
            <td>2</td>
            <td>2</td>
          </tr>
          <tr>
            <td>walk-of-fame</td>
            <td>889</td>
            <td>184</td>
            <td>67</td>
            <td>50</td>
            <td>62</td>
          </tr>
          <tr>
            <td>watching-between-the-lines</td>
            <td>458</td>
            <td>158</td>
            <td>43</td>
            <td>35</td>
            <td>41</td>
          </tr>
          <tr>
            <td>whats-my-ride</td>
            <td>362</td>
            <td>131</td>
            <td>2</td>
            <td>8</td>
            <td>9</td>
          </tr>
          <tr>
            <td>youve-got-this-covered</td>
            <td>289</td>
            <td>160</td>
            <td>22</td>
            <td>3</td>
            <td>4</td>
          </tr>
        </tbody>
      </table>
      {/* secondary stats */}
      <table>
        <thead>
          <tr>
            <th>puzzle_id</th>
            <th>top_incorrect</th>
            <th>relative_frequency</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>identify-the-piece</td>
            <td>LITTLEFUGUE</td>
            <td>116.0</td>
          </tr>
          <tr>
            <td>imagine</td>
            <td>APOLOGIZE</td>
            <td>108.3</td>
          </tr>
          <tr>
            <td>eye-spy</td>
            <td>PROVIDENCE</td>
            <td>96.3</td>
          </tr>
          <tr>
            <td>six-degrees</td>
            <td>DANIELRADCLIFFE</td>
            <td>90.6</td>
          </tr>
          <tr>
            <td>narcissism</td>
            <td>SUPERIOR</td>
            <td>90.5</td>
          </tr>
          <tr>
            <td>connect-the-dots</td>
            <td>SHAPES</td>
            <td>89.7</td>
          </tr>
          <tr>
            <td>aha-erlebnis</td>
            <td>GEFUHLPROOF</td>
            <td>86.2</td>
          </tr>
          <tr>
            <td>plagiarism</td>
            <td>CHILLEST</td>
            <td>73.8</td>
          </tr>
          <tr>
            <td>m-guards-n-doors-and-k-choices</td>
            <td>PULLEYS</td>
            <td>52.6</td>
          </tr>
          <tr>
            <td>international-neighbours</td>
            <td>FAVORITE</td>
            <td>51.3</td>
          </tr>
          <tr>
            <td>the-final-heist</td>
            <td>BLIND</td>
            <td>43.0</td>
          </tr>
          <tr>
            <td>two-guards-two-doors</td>
            <td>STEERS</td>
            <td>38.8</td>
          </tr>
          <tr>
            <td>ten-guards-ten-doors</td>
            <td>SIX</td>
            <td>35.6</td>
          </tr>
          <tr>
            <td>whats-my-ride</td>
            <td>APOLLO</td>
            <td>33.6</td>
          </tr>
          <tr>
            <td>opening-sequences</td>
            <td>PAWNTOFF</td>
            <td>28.7</td>
          </tr>
          <tr>
            <td>like-clockwork</td>
            <td>ORANGE</td>
            <td>26.9</td>
          </tr>
          <tr>
            <td>cutting-room-floor</td>
            <td>BILLY</td>
            <td>26.7</td>
          </tr>
          <tr>
            <td>lost-lyric</td>
            <td>SUNDAY</td>
            <td>25.5</td>
          </tr>
          <tr>
            <td>find-ben</td>
            <td>MUSEUM</td>
            <td>25.4</td>
          </tr>
          <tr>
            <td>red-blue</td>
            <td>DATE</td>
            <td>25.0</td>
          </tr>
          <tr>
            <td>the-compact-disc</td>
            <td>KUWAIT</td>
            <td>21.8</td>
          </tr>
          <tr>
            <td>beads</td>
            <td>PRESS</td>
            <td>19.2</td>
          </tr>
          <tr>
            <td>walk-of-fame</td>
            <td>CRUZ</td>
            <td>16.3</td>
          </tr>
          <tr>
            <td>the-guard-and-the-door</td>
            <td>ACTOR</td>
            <td>15.9</td>
          </tr>
          <tr>
            <td>one-guard-screen</td>
            <td>DOUBLESLIT</td>
            <td>15.8</td>
          </tr>
          <tr>
            <td>youve-got-this-covered</td>
            <td>DAY</td>
            <td>15.0</td>
          </tr>
          <tr>
            <td>boring-plot</td>
            <td>EXTRACTION</td>
            <td>13.8</td>
          </tr>
          <tr>
            <td>color-wheel</td>
            <td>FENNEL</td>
            <td>13.3</td>
          </tr>
          <tr>
            <td>watching-between-the-lines</td>
            <td>BATESEED</td>
            <td>12.7</td>
          </tr>
          <tr>
            <td>barbie</td>
            <td>CHATTYKATHY</td>
            <td>11.9</td>
          </tr>
          <tr>
            <td>fridge-magnets</td>
            <td>DIREAP</td>
            <td>10.8</td>
          </tr>
          <tr>
            <td>sound-of-music</td>
            <td>CYANOCOCCUSNINE</td>
            <td>10.2</td>
          </tr>
          <tr>
            <td>constellation</td>
            <td>DURIAN</td>
            <td>9.7</td>
          </tr>
          <tr>
            <td>chain-letters</td>
            <td>THEGATHERINGSTORM</td>
            <td>8.8</td>
          </tr>
          <tr>
            <td>piecemeal</td>
            <td>TEXTALIEN</td>
            <td>8.7</td>
          </tr>
          <tr>
            <td>heist</td>
            <td>FLOORPLANBROWN</td>
            <td>8.5</td>
          </tr>
          <tr>
            <td>a-fistful-of-cards-iv</td>
            <td>ORANGE</td>
            <td>8.4</td>
          </tr>
          <tr>
            <td>balloon-animals</td>
            <td>REALPOPMUSIC</td>
            <td>8.4</td>
          </tr>
          <tr>
            <td>filming-schedule</td>
            <td>BANNED</td>
            <td>5.8</td>
          </tr>
          <tr>
            <td>a-fistful-of-cards</td>
            <td>GRI</td>
            <td>5.7</td>
          </tr>
          <tr>
            <td>eye-to-eye</td>
            <td>MIRRORS</td>
            <td>5.2</td>
          </tr>
          <tr>
            <td>secret-ingredient</td>
            <td>OASISSAND</td>
            <td>5.0</td>
          </tr>
          <tr>
            <td>drop-the</td>
            <td>OLDERIDEAS</td>
            <td>4.9</td>
          </tr>
          <tr>
            <td>fractal-shanty</td>
            <td>MERFOLK</td>
            <td>4.3</td>
          </tr>
          <tr>
            <td>bluenos-puzzle-box</td>
            <td>WHEELING</td>
            <td>4.0</td>
          </tr>
          <tr>
            <td>genetic-counseling</td>
            <td>JOLENE</td>
            <td>3.6</td>
          </tr>
          <tr>
            <td>financial-crimes-3</td>
            <td>ACTORSEQUITYPRIVATEFIRM</td>
            <td>3.6</td>
          </tr>
          <tr>
            <td>a-fistful-of-cards-ii</td>
            <td>SPRING</td>
            <td>3.2</td>
          </tr>
          <tr>
            <td>eye-of-the-storm</td>
            <td>TROPICS</td>
            <td>3.1</td>
          </tr>
          <tr>
            <td>peanuts</td>
            <td>PROTOHUMAN</td>
            <td>2.7</td>
          </tr>
          <tr>
            <td>heist-ii</td>
            <td>SPRING</td>
            <td>2.4</td>
          </tr>
          <tr>
            <td>a-fistful-of-cards-iii</td>
            <td>FIGHTLE</td>
            <td>2.3</td>
          </tr>
          <tr>
            <td>hand-letters</td>
            <td>LUNULE</td>
            <td>2.1</td>
          </tr>
          <tr>
            <td>are-you-sure</td>
            <td>COMBINATION</td>
            <td>2.1</td>
          </tr>
          <tr>
            <td>the-snack-zone</td>
            <td>SAUVINGNON</td>
            <td>1.5</td>
          </tr>
          <tr>
            <td>heist-iii</td>
            <td>IMPOSSIBLE</td>
            <td>1.4</td>
          </tr>
        </tbody>
      </table>
      {/* MISCELLANEOUS STATS */}
      {/* first solves */}
      <table>
        <thead>
          <tr>
            <th>interaction_type</th>
            <th>puzzle_id</th>
            <th>display_name</th>
            <th>solve_duration</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>in-person</td>
            <td>walk-of-fame</td>
            <td>meowmeow</td>
            <td>0m 14.178s</td>
          </tr>
          <tr>
            <td>remote-box</td>
            <td>two-guards-two-doors</td>
            <td>✈✈✈ galactic procrastinators ✈✈✈</td>
            <td>5m 0.897s</td>
          </tr>
          <tr>
            <td>remote</td>
            <td>two-guards-two-doors</td>
            <td>Theatre Screen's Bright Illumination</td>
            <td>7m 20.635s</td>
          </tr>
        </tbody>
      </table>
      {/* longest guesses */}
      <table>
        <thead>
          <tr>
            <th>guess</th>
            <th>length</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              THISISJUSTANAAOCTAVEASTHEBASSPARTANDITSBEENSHORTENEDABUNCHANDTHEREABIGGAPHEREIDKWHATELSEYOUWANT
            </td>
            <td>95</td>
          </tr>
          <tr>
            <td>
              OOOOOOOOOOOAAAAEAAIAUJOOOOOOOOOOOOOAAEOAAUUAEEEEEEEEEAAAAEAEIEAJOOOOOOOOOOEEEEOAAAAAAAA
            </td>
            <td>87</td>
          </tr>
          <tr>
            <td>
              ASIFWALTZBYGEORDIEGREEPLISTENTOTHENEWSOUNDTODAYTHEBESTALBUMOFTWENTYTWENTYFOUR
            </td>
            <td>77</td>
          </tr>
          <tr>
            <td>
              FUNFACTTHERAFSTARTEDTHECARROTSMYTHWHENWHATTHEIRPILOTSACTUALLYHADWASRADAR
            </td>
            <td>72</td>
          </tr>
          <tr>
            <td>
              HTTPSWWWBROWNPUZZLEHUNTCOMNEXTIMAGEURLFNEXTFSTATICFMEDIAFSNACKBEJPGWQ
            </td>
            <td>69</td>
          </tr>
          <tr>
            <td>
              AARGHWHICHISTHERIGHTSHAKESPEARESOURCETHATMATCHESYOURLINENUMBERS
            </td>
            <td>63</td>
          </tr>
          <tr>
            <td>
              SINKCALPUREVLIGOLINDIGOLINDIHWOLPRELACKNIDNIGOLINKCALISETILE
            </td>
            <td>60</td>
          </tr>
          <tr>
            <td>
              ATLEASTWITHTHEPREVIOUSONEYOUCANGETITFROMNUTRIMATICWITHETUDES
            </td>
            <td>60</td>
          </tr>
          <tr>
            <td>WHEREDIDICOMEFROMWHEREDIDIGOWHEREDIDICOMEFROMCOTTONEYEDJOE</td>
            <td>58</td>
          </tr>
          <tr>
            <td>WAITISITJUSTNORMALMONTYHALLANDWEDONTCAREABOUTTHEBULLCRAP</td>
            <td>56</td>
          </tr>
          <tr>
            <td>IDKWHATTHISPUZZLEISABOUTBUTILOVETHELONGESTJOHNSYAY</td>
            <td>50</td>
          </tr>
          <tr>
            <td>THERESNOPUZZLEHEREJUSTFUCKINGFLAVORTEXTWHATTHEFUCK</td>
            <td>50</td>
          </tr>
          <tr>
            <td>LETSWATCHEXPERTSTRYTOPUZZLEATSOMERIDDLESINADESERT</td>
            <td>49</td>
          </tr>
          <tr>
            <td>LETSWATCHEXPERTSTRYTOPUZZLEATSOMERIDDLESINADESERT</td>
            <td>49</td>
          </tr>
          <tr>
            <td>LETSWATCHEXPERTSTRYTOPUZZLEATSOMERIDDLESINADESERT</td>
            <td>49</td>
          </tr>
          <tr>
            <td>LETSWATCHEXPERTSTRYTOPUZZLEATSOMERIDDLESINADESERT</td>
            <td>49</td>
          </tr>
          <tr>
            <td>IFYOUWANTMETOSTOPSENDMEADMITSPROCYONINPUZZLEWORLD</td>
            <td>49</td>
          </tr>
          <tr>
            <td>LETSWATCHEXPERTSTRYTOPUZZLEATSOMERIDDLESINADESERT</td>
            <td>49</td>
          </tr>
          <tr>
            <td>LETSWATCHEXPERTSTRYTOPUZZLEATSOMERIDDLESINADESERT</td>
            <td>49</td>
          </tr>
          <tr>
            <td>LETSWATCHEXPERTSTRYTOPUZZLEATSOMERIDDLESINADESERT</td>
            <td>49</td>
          </tr>
          <tr>
            <td>LETSWATCHEXPERTSTRYTOPUZZLEATSOMERIDDLESINADESERT</td>
            <td>49</td>
          </tr>
          <tr>
            <td>LETSWATCHEXPERTSTRYTOPUZZLEATSOMERIDDLESINADESERT</td>
            <td>49</td>
          </tr>
          <tr>
            <td>LETSWATCHEXPERTSTRYTOPUZZLEATSOMERIDDLESINADESERT</td>
            <td>49</td>
          </tr>
          <tr>
            <td>LETSWATCHEXPERTSTRYTOPUZZLEATSOMERIDDLESINADESERT</td>
            <td>49</td>
          </tr>
          <tr>
            <td>LETSWATCHEXPERTSTRYTOPUZZLEATSOMERIDDLESINADESERT</td>
            <td>49</td>
          </tr>
        </tbody>
      </table>
      {/* shortest guesses */}
      <table>
        <thead>
          <tr>
            <th>guess</th>
            <th>length</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>K</td>
            <td>1</td>
          </tr>
          <tr>
            <td>I</td>
            <td>1</td>
          </tr>
          <tr>
            <td>J</td>
            <td>1</td>
          </tr>
          <tr>
            <td>H</td>
            <td>1</td>
          </tr>
          <tr>
            <td>R</td>
            <td>1</td>
          </tr>
          <tr>
            <td>L</td>
            <td>1</td>
          </tr>
          <tr>
            <td>O</td>
            <td>1</td>
          </tr>
          <tr>
            <td>K</td>
            <td>1</td>
          </tr>
          <tr>
            <td>A</td>
            <td>1</td>
          </tr>
          <tr>
            <td>O</td>
            <td>1</td>
          </tr>
        </tbody>
      </table>
      {/* shortest hints */}
      <table>
        <thead>
          <tr>
            <th>request</th>
            <th>length</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td></td>
            <td>0</td>
          </tr>
          <tr>
            <td>jk\n</td>
            <td>3</td>
          </tr>
          <tr>
            <td>GIARRE</td>
            <td>6</td>
          </tr>
          <tr>
            <td>no clue</td>
            <td>7</td>
          </tr>
          <tr>
            <td>CHILLEST</td>
            <td>8</td>
          </tr>
          <tr>
            <td>Hint on start</td>
            <td>13</td>
          </tr>
          <tr>
            <td>ignore this\n\n</td>
            <td>13</td>
          </tr>
          <tr>
            <td>What does BLUENO mean?</td>
            <td>23</td>
          </tr>
          <tr>
            <td>is it related to course timings?\n</td>
            <td>33</td>
          </tr>
          <tr>
            <td>We're not sure where to start here</td>
            <td>34</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}
